const phone='5519999287766';
const serviceIconStyle=document.createElement('style');serviceIconStyle.textContent='.service-grid article>span{display:none}';document.head.append(serviceIconStyle);
const mobileSafetyStyle=document.createElement('style');mobileSafetyStyle.textContent='body{overflow-x:hidden}@media(max-width:760px){.site-header:has(#menu.open)~.quick-contacts{display:none}.hero-content{padding-top:7.5rem}.product-price strong{font-size:1.55rem}.page-hero h1{overflow-wrap:anywhere}.route-plan{white-space:nowrap}}';document.head.append(mobileSafetyStyle);
const aboutEyebrow=document.querySelector('.about .eyebrow');if(aboutEyebrow)aboutEyebrow.textContent='POR TRÁS DA RUD VIAGENS';
if(!location.pathname.includes('/roteiros/')){const footerLinks=document.querySelector('footer div');if(footerLinks)footerLinks.remove();const quickContacts=document.createElement('nav');quickContacts.className='quick-contacts';quickContacts.setAttribute('aria-label','Canais de contato rápido');quickContacts.innerHTML=`<a class="quick-contact" data-whatsapp data-message="Olá! Quero falar com a Rud Viagens." aria-label="Falar no WhatsApp"><img src="assets/icons/whatsapp.svg" alt="">WhatsApp</a><a class="quick-contact" href="https://www.instagram.com/rud.viagens/" target="_blank" rel="noopener noreferrer" aria-label="Abrir Instagram da Rud Viagens"><img src="assets/icons/instagram.svg" alt="">Instagram</a>`;document.body.append(quickContacts);const contactStyle=document.createElement('style');contactStyle.textContent=`.quick-contacts{position:fixed;top:88px;right:20px;z-index:20;display:flex;gap:.15rem;padding:.32rem;background:#ffffffed;border:1px solid #ffffff99;border-radius:999px;box-shadow:0 10px 28px #092a4038;backdrop-filter:blur(10px)}.quick-contact{display:flex;align-items:center;gap:.48rem;padding:.54rem .76rem;border-radius:999px;color:#16384d;font:700 .78rem/1 Arial,sans-serif}.quick-contact:hover{background:#edf5f7}.quick-contact img{width:19px;height:19px}@media(max-width:760px){.quick-contacts{top:74px;right:12px}.quick-contact{width:38px;height:38px;justify-content:center;padding:0;font-size:0}.quick-contact img{width:20px;height:20px}}`;document.head.append(contactStyle);}
function whatsapp(scope=document){scope.querySelectorAll('[data-whatsapp]').forEach(link=>{link.href=`https://wa.me/${phone}?text=${encodeURIComponent(link.dataset.message||'Olá! Quero falar com a Rud Viagens.')}`;link.target='_blank';link.rel='noopener noreferrer';});}
function card(item){return `<article class="experience-card ${item.featuredWide?'experience-card--wide':''}"><img src="${item.image}" alt="${item.alt}"><div class="experience-card__body"><p class="tag">${item.category}</p><h3>${item.name}</h3><p>${item.short}</p><a href="${item.href}">Conhecer experiência <span>→</span></a></div></article>`;}
const featured=document.querySelector('[data-featured-experiences]');if(featured)featured.innerHTML=RUD_CATALOG.featured.map(card).join('');
const isRoutePage=location.pathname.includes('/roteiros/');
if(isRoutePage){const header=document.querySelector('header');if(header&&!header.classList.contains('route-header')){header.className='route-header';header.innerHTML=`<a class="brand" href="../index.html" aria-label="Voltar para a página inicial da Rud Viagens"><img src="../assets/logo-rud-instagram.jpg" alt="Rud Viagens"><span>RUD <b>VIAGENS</b></span></a><div class="route-actions"><a class="route-back" href="../index.html#experiencias">← Experiências</a><a class="route-plan" data-whatsapp data-message="Olá! Quero planejar uma viagem com a Rud Viagens.">Planejar viagem</a></div>`;}const routeStyle=document.createElement('style');routeStyle.textContent=`.route-header{min-height:74px;box-shadow:0 2px 15px #092a4012;background:#fffffff2!important}.route-actions{display:flex;align-items:center;gap:1.2rem}.route-back{font-size:.85rem;font-weight:800;color:#075caa}.route-plan{border-radius:999px;background:#f36c21;padding:.68rem 1rem;color:#fff;font-size:.8rem;font-weight:800}@media(max-width:760px){.route-header{min-height:64px;padding:.55rem 1rem}.route-header .brand img{width:38px;height:38px}.route-header .brand span{font-size:.75rem}.route-actions{gap:.65rem}.route-back{font-size:.75rem}.route-plan{padding:.55rem .7rem;font-size:.72rem}}`;document.head.append(routeStyle);}
if(isRoutePage){const header=document.querySelector('header');if(header){header.className='route-header';header.innerHTML=`<a class="brand" href="../index.html" aria-label="Voltar para a página inicial da Rud Viagens"><img src="../assets/logo-rud-instagram.jpg" alt="Rud Viagens"><span>RUD <b>VIAGENS</b></span></a><div class="route-actions"><a class="route-back" href="../index.html#experiencias">← Experiências</a><a class="route-plan" data-whatsapp data-message="Olá! Quero planejar uma viagem com a Rud Viagens.">Planejar viagem</a></div>`;}}
const menuButton=document.querySelector('.menu-button'),menu=document.querySelector('#menu');if(menuButton&&menu)menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',open);menuButton.textContent=open?'×':'☰';});if(menu)menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');if(menuButton){menuButton.setAttribute('aria-expanded','false');menuButton.textContent='☰';}}));const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();whatsapp();
